# Chapter 1
---

## 1. Install Python and Jupyter Notebook

## 2. Introduction to Python and Jupyter Notebook

## 3. Hot key for Jupyter Notebook

### 1) Command Mode
 * [a] 위로 셀 추가
 * [b] 아래로 셀 추가
 * [d,d], [x] 선택 셀 삭제
 * [c] 선택 셀 복사
 * [p] 선택 셀 아래에 붙여넣기
 * [shift]+[m] 아래 셀과 합치기
 * [m] 마크다운으로 변경
 * [y] 코드로 변경
 * [s] 파일 저장
 * [enter] 선택 셀의 입력 모드

### 2) Edit Mode
 * [ctrl]+[a] 코드 전체 선택
 * [ctrl]+[z] 선택 셀 내 실행 취소
 * [ctrl]+[y] 선택 셀 내 다시 실행
 * [ctrl]+[/] 커서 위치 라인 주석처리
 * [ctrl]+[enter] 코드 실행
 * [shift]+[enter] 코드 실행 후 다음 셀로 이동 (없는 경우 추가)
 * [shift]+[ctrl]+[-] 커서 위치에서 셀 둘로 나누기
 * [esc], [ctrl]+[m] 셀 선택 모드

## 4. 파이썬 프로그램 기본

### 1) 사칙연산
* +, -, *, **, /, %(모듈러)

### 2) 데이터형 
* type()
 * a) 문자열형(str)
 * b) 수치형 (int, float)
 * c) 부울형 (bool) 

### 3) 제어문
* **a) if문**

In [17]:
N = int(input("입력하는 숫자는 6과 20 사이의 짝수인가?: "))
if N >=6 and N <=20:
    if N % 2 == 0:
        print ("Yes")
    else: print("No")
else: print("No")

입력하는 숫자는 6과 20 사이의 짝수인가?: 31
No


* **b) for문**
 * for val in sequence (리스트, 튜플, 문자열)
 * 여러 리스트에서 요소와 인덱스를 동시에 얻으려면  
   i) enumerate() 함수 : for문 결과 출력시 인덱스 추출  
   ii) zip() 함수 : 여러 리스트를 함께 for문에 돌리는 경우 사용 

In [18]:
a = [1, 2, 3, 4]
res = [num*3 for num in a if num % 2 ==0]
print(res)

[6, 12]


In [21]:
# enumerate()은 인덱스 번호와 컬렉션의 원소를 튜플 형태로 반환 +1
# zip()은 여러 개의 순회 가능한(iterable) 객체를 인자로 받아 동일한 개수로 이루어진 자료형을 묶어서 튜플의 형태로 반환
names = ['Song', 'Kim', 'Lee']
ages = [24, 50, 18]
for i, (name, age) in enumerate(zip(names,ages)):
    print(i, name, age)

0 Song 24
1 Kim 50
2 Lee 18


* **c) while문**
 * 루프 내 continue 만나면 해당 루프 종료 후 루프 시작지점으로 돌아감 (if, for, while문 모두)
 * try/except 문을 이용해 오류 처리 가능

In [23]:
# 1부터 n까지 정수합 출력

n = int(input("Enter n : "))
sum = 0
i = 1
while i <= n:
    sum = sum + i
    i += 1
print("The sum is", sum)

Enter n : 5
The sum is 15


In [26]:
# done 입력 전까지 숫자 합, 개수, 몫 출력

num = 0
tot = 0.0

while True:
    sval = input("Enter a number:")
    if sval == 'done':
        break
        
# try 문에서 예외 발생시 except 문 실행
    try:
        fval = float(sval) # 수치형 변수인지 확인
    except:
        print("Invalid input")
        continue
    num += 1
    tot = tot + fval
print(tot, num, tot/num)

Enter a number:4
Enter a number:2
Enter a number:done
6.0 2 3.0


In [29]:
# try 문에서 문자열 정수로 전환되지 않아 except문 실행
astr = "호"
try:
    print("Hello")
    isInt = int(astr) 
    print("World")
except:
    isInt = "Integer로 변환할 수 없습니다."
print("Done", isInt)

Hello
Done Integer로 변환할 수 없습니다.


In [30]:
astr = "123"
try:
    print("Hello")
    isInt = int(astr)
    print("World")
except:
    isInt = "Integer로 변환할 수 없습니다."
print("Done", isInt)

Hello
World
Done 123


## 5. Packages
* R은 cmd, package, Python은 module
### 1) Install Packages
### 2) Some Packages
 * numpy : 배열(ndarray) 데이터를 다루는 클래스를 주로 사용, 행렬 연산에 강함
 * pandas : 데이터프레임(dataframe) 데이터 관리에 강한 클래스 사용, 통계분석에 필수적
 * Sklearn : classification (분류), regression (회귀), clustering (클러스터링), sufficient dimension (차원축소) 등 다양한 머신러닝 모델링을 지원
 * Tensorflow : 구글에서 제공하는 머신러닝 및 딥러닝 개발을 위한 패키지
 * matplotlib, seaborn # 강의안? +1

## 6. 자료구조

### 1) List
* **a) 리스트 생성 [ ]** #+1

In [124]:
sample_list=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

a=sample_list[0:9:2] 
print(f'sample_list[0:9:2] : {a}', '\n from 0 to 9-1, step by 2' )
a=sample_list[slice(0,9,2)] 
print(f'sample_list[slice(0,9,2)] : {a}', '\n from 0 to 9-1, step by 2')
a=sample_list[::-1] 
print(f'sample_list[::-1] : {a}', '\n all items, reversed')
a=sample_list[1::-1] 
print(f'sample_list[1::-1] : {a}', '\n from 1, reversed')
a=sample_list[:-4] 
print(f'sample_list[-4:] : {a}', '\n 처음부터 [-5]까지 출력')
a=[sample_list[i] for i in [0, 2, 4]] 
print(f'[sample_list[i] for i in [0, 2, 4]]  : {a}')
a=sample_list[2::] 
print(f'sample_list[2::] : {a}', '\n [2] 기준으로 오른쪽 모든 값 출력')
a=sample_list[2::-1]
print(f'sample_list[2::-1] : {a}', '\n [2] 기준으로 오른쪽 모든 값의 reversed 출력')
a=sample_list[:-3:] 
print(f'sample_list[:-3:] : {a}', '\n [-3-1] 기준으로 왼쪽 모든 값 출력 (step by 1=default)')
a=sample_list[:-3:-1] 
print(f'sample_list[:-3:-1] : {a}', '\n [-3-1] 기준으로 왼쪽 모든 값의 reversed 출력')
a=sample_list[-3::-1] 
print(f'sample_list[-3::-1] : {a}', '\n from -3, reversed')

sample_list[0:9:2] : [1, 3, 5, 7, 9] 
 from 0 to 9-1, step by 2
sample_list[slice(0,9,2)] : [1, 3, 5, 7, 9] 
 from 0 to 9-1, step by 2
sample_list[::-1] : [10, 9, 8, 7, 6, 5, 4, 3, 2, 1] 
 all items, reversed
sample_list[1::-1] : [2, 1] 
 from 1, reversed
sample_list[-4:] : [1, 2, 3, 4, 5, 6] 
 처음부터 [-5]까지 출력
[sample_list[i] for i in [0, 2, 4]]  : [1, 3, 5]
sample_list[2::] : [3, 4, 5, 6, 7, 8, 9, 10] 
 [2] 기준으로 오른쪽 모든 값 출력
sample_list[2::-1] : [3, 2, 1] 
 [2] 기준으로 오른쪽 모든 값의 reversed 출력
sample_list[:-3:] : [1, 2, 3, 4, 5, 6, 7] 
 [-3-1] 기준으로 왼쪽 모든 값 출력 (step by 1=default)
sample_list[:-3:-1] : [10, 9] 
 [-3-1] 기준으로 왼쪽 모든 값의 reversed 출력
sample_list[-3::-1] : [8, 7, 6, 5, 4, 3, 2, 1] 
 from -3, reversed


* **c) 리스트 연산**
 * len(), del(), 덧셈(+), 곱셈(*)
 
* **d) 리스트 메서드**
 * list.append(value or list)
 * list.insert(index, value) : index위치에 추가, 기존 값 오른쪽으로 밀림
 * list.remove(value) : 여러개 존재시 첫번째 값을 제거
 * list.pop() : 맨 마지막 값 반환 후 삭제
 * list.extend(list2) : list에 list2 연결
 * list.copy() : 다른 변수로 지정
 * list.reverse() 
 * list.sort() : 내부요소의 데이터타입이 동일해야함, reverse=True 변수
 * list.count(value) : 반환값
 * list.index(value) : 반환값
 * list.clear() : 모든 값 삭제 *** +1 (강의안 오류 확인)
 
 
### 2) Array

* **a) array 생성**

In [242]:
import numpy as np

sample_array = np.array([1, 2, 3, 4, 5])
print(sample_array)
sample_array2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(sample_array2)
print(type(sample_array2))

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


* **b) 인덱싱과 슬라이싱**

In [101]:
print(sample_array2[0:2,1:3])

[[2 3]
 [7 8]]


* **c) array 속성**
 * 벡터화 계산 (vectorization)
 * 크기가 다른 배열의 경우 '1차원의 길이가 같은 경우'에만 연산 가능 (broadcasting)

In [115]:
#vectorization

arr = np.array([[1., 2., 3.],[4.,5.,6.]])
print(arr.dtype)
print(arr*arr)
print(1/arr*10) 

float64
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[10.          5.          3.33333333]
 [ 2.5         2.          1.66666667]]


In [114]:
# broadcasting

arr1 = np.array([1, 2, 3])
arr2 = np.array([[4, 5, 6], [7, 8, 9]])
arr3 = np.array([1, 2, 3, 4])

print(arr2)
print(arr1+arr2) 
# arr1을 recycling, 긴쪽에 맞춰 반복함. 단 1차원 길이가 같은 경우만 가능

# print(arr1+arr3) : error
# print(arr2+arr3) : error
# 1차원 벡터의 길이가 다른 경우 연산 불가

[[4 5 6]
 [7 8 9]]
[[ 5  7  9]
 [ 8 10 12]]


 ### 3) Data.frame

* **a) 데이터프레임 생성**
 * 배열, 리스트를 이용하는 방법이 간단하며 중괄호 필요

In [243]:
import pandas as pd

# list 이용
df1 = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
print(df1)

# dictionary 이용
data = {
    'age' : [20, 23, 48],
    'height' : [183, 192, 175],
    'weight' : [77, 83, 65],
    'gender' : ["M", "M", "F"]} # character vector
indexName = ['슈퍼맨', '스파이더맨', '베트맨'] # index 생성
df2 = pd.DataFrame(data, index = indexName)
print(df2)

# array 이용
sample_array = np.array([1, 2, 3, 4, 5])
df3 = pd.DataFrame({
    'col1' : sample_array,
    'col2' : sample_array*2,
    'col3' : ["A", "B", "C", "D", "E"]})
print(df3)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
       age  height  weight gender
슈퍼맨     20     183      77      M
스파이더맨   23     192      83      M
베트맨     48     175      65      F
   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E


* 난수 생성
 * np.random.rand(size=1) : 0부터 1사이 균일분포
 * np.random.randn(size=1) : 가우시안 표준정규분포
 * np.random.randint(low, high, size) : 균일분포의 정수난수

In [137]:
np.random.seed(22)
df = pd.DataFrame(np.random.randint(1, 10, size=(3,5)))
print(df)
df.info()

   0  1  2  3  4
0  6  5  1  5  7
1  7  5  9  5  3
2  9  8  3  9  9
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      int32
 1   1       3 non-null      int32
 2   2       3 non-null      int32
 3   3       3 non-null      int32
 4   4       3 non-null      int32
dtypes: int32(5)
memory usage: 188.0 bytes


* **b) 인덱싱**
 * df[], df.query, df.loc, df.iloc

In [142]:
np.random.seed(2022)
df=pd.DataFrame(np.random.randint(10,22,(4,5)), index=["a","b","c","d"],columns=['A','B','C','D','E'])
print(df.shape)
df

(4, 5)


A   B   C   D   E
a  10  11  11  10  17
b  18  12  18  10  15
c  19  11  21  21  13
d  18  21  10  13  16

   i) df [ ] 

In [164]:
# column 추출시 [] 안에 칼럼명 입력, 복수의 경우 리스트 형식
print(df[['A','C']])

# column 추출시 점(.) 이용 가능
print(df.B)

# 지정한 열만 빼고 데이터 추출, axis=1 : 열, axis=0 : 행
print(df.drop("A", axis = 1))

# 조건문을 이용한 데이터 추출
print(df[ (df["A"]>15) | (df["B"]>17) ])

# row 추출, 슬라이싱
print(df["b":"c"])

    A   C
a  10  11
b  18  18
c  19  21
d  18  10
a    11
b    12
c    11
d    21
Name: B, dtype: int32
    B   C   D   E
a  11  11  10  17
b  12  18  10  15
c  11  21  21  13
d  21  10  13  16
    A   B   C   D   E
b  18  12  18  10  15
c  19  11  21  21  13
d  18  21  10  13  16
    A   B   C   D   E
b  18  12  18  10  15
c  19  11  21  21  13


   ii) df.query()

In [159]:
# 인덱스로 column 지정
print(df.query('index == "a"'))

# row에 조건 지정
print(df.query('A == 19 & C == 21'))

# column, row에 모두 조건 지정
print(df.query('A == 19')[["A", "C"]])

    A   B   C   D   E
a  10  11  11  10  17
    A   B   C   D   E
c  19  11  21  21  13
    A   C
c  19  21


   iii) df.loc()
  * df.loc[row 인덱스값]
  * df.loc[row 인덱스값, column 인덱스값]

In [171]:
# row 인덱스
print( df.loc["a"] )

# row 인덱스, 슬라이싱
print( df.loc["a":"c"] ) #loc 대신 []로도 가능
print (df.loc[["b","c"]]) #loc 쓰지 않으면 error +1

# 조건문 이용
print( df.loc[df["A"] > 18])
print( df.loc[df.A > 18])

A    10
B    11
C    11
D    10
E    17
Name: a, dtype: int32
    A   B   C   D   E
a  10  11  11  10  17
b  18  12  18  10  15
c  19  11  21  21  13
    A   B   C   D   E
b  18  12  18  10  15
c  19  11  21  21  13
    A   B   C   D   E
c  19  11  21  21  13
    A   B   C   D   E
c  19  11  21  21  13


In [176]:
# row 및 column 인덱스
print(df.loc["a","A"])

# row 및 column 인덱스, 슬라이싱 및 리스트 이용
print(df.loc[["a","b"], "C":"E"])

# row 및 column 인덱스, 조건문 이용
print(df.loc[df.A>10, ["C","D"]])

10
    C   D   E
a  11  10  17
b  18  10  15
    C   D
b  18  10
c  21  21
d  10  13


   iv) df.iloc()
  * 정수 인덱스만을 받음, [row] 혹은 [row, col] 가능

In [178]:
# row 인덱스
print(df.iloc[-1])

# row 및 column 인덱스
print(df.iloc[:2, 2])

A    18
B    21
C    10
D    13
E    16
Name: d, dtype: int32
a    11
b    18
Name: C, dtype: int32


* **c) 데이터프레임 속성**
 * df.axes : row 및 column 축 반환
 * df.index
 * df.values : 넘파이 array 형식으로 반환 (행/열이름 제외)
 * df.ndim : 차원 나타내는 int 반환
 * df.shape : 크기를 나타내는 튜플 반환
 * df.size : 크기를 나타내는 int 반환 (데이터개수)
 * df.dtypes : column별 dtype
 * df.count() : axis=0 col 기준, axis=1 row 기준
 * df.describe()  
*파이썬은 factor변수가 없음



## 7. 파일을 읽어 들이는 방법
* Pandas가 데이터프레임으로 읽어들일 수 있는 포맷들  
  : CSV (comma seperated value, 로딩시 에러가 거의 없음), Excel, HTML, JSON, HDF5, SAS, STATA, SQSL
* %%writefile : 셀에 서술한 내용대로 텍스트파일을 만드는 명령, 디렉토리에 새 파일 생성함
* read_csv 파라미터
  * filepath/buffer.csv
  * sep/delimiter : default ',', '\s+'는 정규식문자열로 길이가 정해지지 않은 공백이 구분자
  * header : default 0, 컬럼명
  * names : 변수명
  * index_col : 인덱스로 사용할 열의 번호
  * skiprows : 첫행 기준 데이터를 얼마나 건너뛰고 읽어올지 결정
  * nrows : 파일을 읽어올 행의 수 입력
  * date_parser : 시계열 타입으로 변환할 변수 입력

In [202]:
%%writefile sample1.csv 
c1, c2, c3
1, 1.11, one
2, 2.22, two
3, 3.33, three

Overwriting sample1.csv


### 1) csv 파일 입력

In [220]:
# working directory에 파일이 있을 때 파일명 입력
print(pd.read_csv('sample1.csv'))

# 파일경로 입력
print(pd.read_csv(r"C:\Users\Jaewon\Bigdata/sample1.csv"))
# 경로가 긴 경우 'r'(raw string)은 문자 그대로 받아들여 달라고 요청

   c1    c2      c3
0   1  1.11     one
1   2  2.22     two
2   3  3.33   three
   c1    c2      c3
0   1  1.11     one
1   2  2.22     two
2   3  3.33   three


### 2) csv 파일 출력

In [218]:
df.to_csv('sample3.csv')

# type 함수 사용한 파일 내용 확인
!type sample3.csv 

# sep 인수로 구분자 변경
df.to_csv('sample4.csv', sep='|')
!type sample4.csv 

,A,B,C,D,E
a,10,11,11,10,17
b,18,12,18,10,15
c,19,11,21,21,13
d,18,21,10,13,16
|A|B|C|D|E
a|10|11|11|10|17
b|18|12|18|10|15
c|19|11|21|21|13
d|18|21|10|13|16


### 3) 인터넷 상의 csv 파일 입력

In [221]:
math = pd.read_csv("http://home.ewha.ac.kr/~josong/dm/mathcat.data", sep = '\s+')
math.describe()

hsgpa      hsengl
count  394.000000  394.000000
mean    79.737563   76.286802
std      6.056138    8.426994
min     65.000000   50.000000
25%     75.700000   71.000000
50%     78.700000   77.000000
75%     83.000000   83.000000
max     96.200000   96.000000

### 4) 데이터 확인

In [223]:
# pandas 옵션 설정으로 앞 뒤 일부분만 보여주는 방법
pd.set_option("display.max_row", 10) # 앞뒤 합쳐 총 10행만 보여줌
pd.set_option("display.max_column", None) # 모든 컬럼 보여줌
math

hsgpa  hsengl hscalc    course passed outcome
1     78.0      80    Yes  Mainstrm     No  Failed
2     66.0      75    Yes  Mainstrm    Yes  Passed
3     80.2      70    Yes  Mainstrm    Yes  Passed
4     81.7      67    Yes  Mainstrm    Yes  Passed
5     86.8      80    Yes  Mainstrm    Yes  Passed
..     ...     ...    ...       ...    ...     ...
390   88.3      90    Yes  Mainstrm    Yes  Passed
391   77.0      79    Yes  Mainstrm    Yes  Passed
392   80.7      70    Yes  Mainstrm    Yes  Passed
393   80.7      81    Yes  Mainstrm    Yes  Passed
394   82.2      86    Yes  Catch-up    Yes  Passed

[394 rows x 6 columns]

## 8. 함수 만들기
* 함수 : 원하는 반복 작업을 위한 입력 -> 실행 -> 외부 출력으로 이루어진 코드묶음
* **Syntax1**  
  def 함수이름 (매개변수): return 결과
* **Syntax2**  
  lambda 매개변수 : 결과

In [225]:
# 피보나치 수열 출력 함수 1
def fib(n):
  """Print a Fibonacci series up to n"""
  a, b = 0,1
  while a < n:
    print(a, end = ' ')
    a, b = b, a+b
fib(2000)

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 

In [226]:
# 피보나치 수열 출력 함수 2
def fib2(n):
  """Return a Fibonacci series up to n"""
  res = [] # list object 지정
  a, b = 0,1
  while a < n:
    res.append(a)
    a, b = b, a+b
  return res
fib2(2000)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597]

In [253]:
# 피보나치 수열 출력 함수 3 - lambda 이용 +1
print(len(fib2(2000)))
fib = lambda n : n if n<2 else fib(n-1) + fib(n-2)
for i in range(1,18):
  print(fib(i), end = ' ')

18
1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 

In [256]:
# 피보나치 수열 출력 함수 4 - map() 이용, 두개의 인수를 가지는 함수 ; 수업중 확인안함 +1???
in1 = [1, 3, 5, 7]
in2 = [2, 4, 6, 8]
list(map(lambda x, y : x+y, in1, in2))

[3, 7, 11, 15]

In [257]:
# 추가로 제시해주신 함수코드짜기

def mysum1(n):
  res=0
  for i in range(1, (n+1)):
    res = res+i
  return res

def mysum2(n):
  res=0
  i = 1
  while i<= n:
    res = res+i
    i=i+1
  return(res)
  
print(mysum1(10),mysum2(10))

55 55


## 9. 모듈 다루기
### 1) 모듈이란?
* 프로그램이 길어짐에 따라 디버깅, 유지를 쉽게 하려고 여러 개의 파일로 나누어 코딩하거나, 각 프로그램에서 썼던 편리한 함수를 복사하지 않고도 사용 가능
* 모듈 (.py)
   * def와 문장들을 넣어 스크립트 및 인터프리터의 대화형 모드에서 사용할 수 있는 파일 (.py)
   * 파이썬 코드로 구성된 파일, 함수/클래스/변수 정의 가능
 * 함수<모듈<패키지
 * 클래스 : 프로그램의 원형, 변수 정의, 함수 등으로 구성되어 있음
 
### 2) 모듈 만들기

* **method1**
  * 주피터노트북에서 file=>save as 선택, 폴더지정없이 바로 파일 이름 작성
  * 지정한 이름으로 탭이름이 바뀌고 Home 폴더에 .ipynb 파일이 저장됨
  * 주피터노트북 실행 후 In 라인에 코드 입력시 Home 폴더에 .py 형식의 모듈이 만들어짐
  
> !jupyter nbconvert--to python pdfplt.ipynb ## +1 실행 되는지??


* **method2**
  * 주피터노트북에서 file=>Download as=>Python(.py) 선택시 다운로드 폴더에 .py 형식의 모듈이 만들어짐

In [259]:
def normplt(m,s):

    import numpy as np

    import matplotlib.pyplot as plt

    from scipy.stats import norm

    x=np.arange(m-3*s,m+3*s,0.1)

    plt.plot(x,norm.pdf(x,m,s),'b')

    plt.title('Normal(Mean=' + str(m) +',STD='+str(s)+')PDF')

    plt.show()



def gamplt(a,b):

    import numpy as np

    import matplotlib.pyplot as plt

    from scipy.stats import gamma

    x=np.arange(0,a*b+6*a*b*b,0.1)

    plt.plot(x,gamma.pdf(x,a,b),'b')

    plt.title('Gamma(Alpha='+str(a)+',Beta='+str(b)+')PDF')

    plt.show()

### 3) 모듈 사용하기

* from 모듈이름 import 함수이름1, 함수이름2


In [262]:
import matplotlib.pyplot as plt

In [263]:
from pdfplt import gamplt, normplt
plt.subplot(2,1,1) # nrows=2, ncols=1, index=1
gamplt(2,1)
plt.subplot(2,1,1) # nrows=2, ncols=1, index=1
normplt(2,1)

ModuleNotFoundError: No module named 'pdfplt'